/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyGroupsRouteImport } from './routes/study-groups'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSchoolIdLoginRouteImport } from './routes/api/public/school-id-login'

const StudyGroupsRoute = StudyGroupsRouteImport.update({
  id: '/study-groups',
  path: '/study-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchoolIdLoginRoute = ApiPublicSchoolIdLoginRouteImport.update({
  id: '/api/public/school-id-login',
  path: '/api/public/school-id-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/study-groups': typeof StudyGroupsRoute
  '/api/public/school-id-login': typeof ApiPublicSchoolIdLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/study-groups': typeof StudyGroupsRoute
  '/api/public/school-id-login': typeof ApiPublicSchoolIdLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/study-groups': typeof StudyGroupsRoute
  '/api/public/school-id-login': typeof ApiPublicSchoolIdLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/connections'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/signup'
    | '/study-groups'
    | '/api/public/school-id-login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/connections'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/signup'
    | '/study-groups'
    | '/api/public/school-id-login'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/connections'
    | '/dashboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/profile'
    | '/projects'
    | '/resources'
    | '/signup'
    | '/study-groups'
    | '/api/public/school-id-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  StudyGroupsRoute: typeof StudyGroupsRoute
  ApiPublicSchoolIdLoginRoute: typeof ApiPublicSchoolIdLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-groups': {
      id: '/study-groups'
      path: '/study-groups'
      fullPath: '/study-groups'
      preLoaderRoute: typeof StudyGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/school-id-login': {
      id: '/api/public/school-id-login'
      path: '/api/public/school-id-login'
      fullPath: '/api/public/school-id-login'
      preLoaderRoute: typeof ApiPublicSchoolIdLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ConnectionsRoute: ConnectionsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  StudyGroupsRoute: StudyGroupsRoute,
  ApiPublicSchoolIdLoginRoute: ApiPublicSchoolIdLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
